"""Milestone 1A scene-format and decoder interfaces."""

from .canonical import (
    CANONICAL_FIELD_COUNT,
    CANONICAL_PROPERTY_NAMES,
    CANONICAL_RECORD_BYTES,
    CANONICAL_REQUIRED_RECORD_BYTES,
    CanonicalComparison,
    CanonicalInspection,
    CanonicalScene,
    compare_canonical_ply,
    compare_scenes,
    load_canonical_ply,
    read_canonical_ply,
    validate_canonical_ply,
    validate_canonical_schema,
    write_canonical_ply,
)
from .compressed import (
    CompressedInspection,
    inspect_compressed_ply,
    validate_compressed_ply,
)
from .decoder import (
    DecodeReport,
    decode_compressed_ply,
    run_decoder,
)
from .errors import (
    DecoderError,
    DecoderInvocationError,
    DecoderUnavailableError,
    MemoryBudgetExceeded,
    OutputExistsError,
    PLYError,
    PLYHeaderError,
    PLYPayloadError,
    PLYSchemaError,
    PLYValidationError,
    SourceChangedError,
    UnsafePathError,
)
from .fingerprint import FileFingerprint, fingerprint_file, sha256_file, sha256_path
from .gaussian_scene import GaussianScene, load_scene, read_scene
from .memory import (
    ChildRSSMonitor,
    HARD_MEMORY_LIMIT_BYTES,
    TARGET_MEMORY_BYTES,
    RuntimeMemoryReport,
    current_child_peak_memory_bytes,
    current_peak_memory_bytes,
    measure_runtime_memory,
)
from .paths import (
    MILESTONE_OUTPUT_RELATIVE,
    find_repository_root,
    milestone_output_root,
    resolve_safe_output_path,
    safe_output_path,
)

__all__ = [
    "CanonicalComparison",
    "CanonicalInspection",
    "CanonicalScene",
    "ChildRSSMonitor",
    "CANONICAL_FIELD_COUNT",
    "CANONICAL_PROPERTY_NAMES",
    "CANONICAL_RECORD_BYTES",
    "CANONICAL_REQUIRED_RECORD_BYTES",
    "CompressedInspection",
    "DecodeReport",
    "DecoderError",
    "DecoderInvocationError",
    "DecoderUnavailableError",
    "FileFingerprint",
    "GaussianScene",
    "HARD_MEMORY_LIMIT_BYTES",
    "MILESTONE_OUTPUT_RELATIVE",
    "MemoryBudgetExceeded",
    "OutputExistsError",
    "PLYError",
    "PLYHeaderError",
    "PLYPayloadError",
    "PLYSchemaError",
    "PLYValidationError",
    "RuntimeMemoryReport",
    "SourceChangedError",
    "TARGET_MEMORY_BYTES",
    "UnsafePathError",
    "compare_canonical_ply",
    "compare_scenes",
    "current_peak_memory_bytes",
    "current_child_peak_memory_bytes",
    "decode_compressed_ply",
    "find_repository_root",
    "fingerprint_file",
    "inspect_compressed_ply",
    "load_canonical_ply",
    "load_scene",
    "measure_runtime_memory",
    "milestone_output_root",
    "read_canonical_ply",
    "read_scene",
    "resolve_safe_output_path",
    "run_decoder",
    "safe_output_path",
    "sha256_file",
    "sha256_path",
    "validate_canonical_ply",
    "validate_canonical_schema",
    "validate_compressed_ply",
    "write_canonical_ply",
]
